# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_activity_ezplatform_schedule_new:
    pattern: /activity/ezplatform/schedule/new
    defaults: { _controller: campaignchain.activity.controller.campaignchain.ezplatform.schedule:newAction }

campaignchain_activity_ezplatform_schedule_edit:
    pattern: /activity/ezplatform/schedule/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.campaignchain.ezplatform.schedule:editAction }

campaignchain_activity_ezplatform_schedule_edit_modal:
    pattern: /modal/activity/ezplatform/schedule/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.campaignchain.ezplatform.schedule:editModalAction }

campaignchain_activity_ezplatform_schedule_edit_api:
    pattern: /api/private/activity/ezplatform/schedule/byactivity/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.campaignchain.ezplatform.schedule:editApiAction }
    options:
        expose: true
    
campaignchain_activity_ezplatform_schedule_read:
    pattern: /activity/ezplatform/schedule/{id}
    defaults: { _controller: campaignchain.activity.controller.campaignchain.ezplatform.schedule:readAction }

# REST routes are being created automatically via FOSRestBundle.
campaignchain_activity_ezplatform_rest:
    type:     rest
    prefix:   /api/{version}/p/campaignchain/activity-ezplatform
    resource: CampaignChain\Activity\EZPlatformBundle\Controller\REST\ActivityController